import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:islami/home/quran/sura_title_widget.dart';

class QuranTab extends StatelessWidget {
  List<String> names = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس"
  ];
  List<String> numOfAyah = [
    '7',
    '286',
    '200',
    '176',
    '120',
    '165',
    '206',
    '75',
    '129',
    '109',
    '123',
    '111',
    '43',
    '52',
    '99',
    '128',
    '111',
    '110',
    '98',
    '135',
    '112',
    '78',
    '118',
    '64',
    '77',
    '227',
    '93',
    '88',
    '69',
    '60',
    '34',
    '30',
    '73',
    '54',
    '45',
    '83',
    '182',
    '88',
    '75',
    '85',
    '54',
    '53',
    '89',
    '59',
    '37',
    '35',
    '38',
    '29',
    '18',
    '45',
    '60',
    '49',
    '62',
    '55',
    '78',
    '96',
    '29',
    '22',
    '24',
    '13',
    '14',
    '11',
    '11',
    '18',
    '12',
    '12',
    '30',
    '52',
    '52',
    '44',
    '28',
    '28',
    '20',
    '56',
    '40',
    '31',
    '50',
    '40',
    '46',
    '42',
    '29',
    '19',
    '36',
    '25',
    '22',
    '17',
    '19',
    '26',
    '30',
    '20',
    '15',
    '21',
    '11',
    '8',
    '8',
    '19',
    '5',
    '8',
    '8',
    '11',
    '11',
    '8',
    '3',
    '9',
    '5',
    '4',
    '7',
    '3',
    '6',
    '3',
    '5',
    '4',
    '5',
    '6'
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Image.asset('assets/images/quran_header_image.png'),
        Table(
          border: TableBorder(
            verticalInside:
                BorderSide(width: 3, color: Theme.of(context).accentColor),
          ),
          children: [
            TableRow(
              decoration: BoxDecoration(
                  border: Border(
                top: BorderSide(width: 3, color: Theme.of(context).accentColor),
                bottom:
                    BorderSide(width: 3, color: Theme.of(context).accentColor),
              )),
              children: [
                Padding(
                  padding: const EdgeInsets.all(10.0),
                  child: Text(
                    AppLocalizations.of(context)!.verses_number,
                    style: Theme.of(context).textTheme.headline4,
                    textAlign: TextAlign.center,
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(10.0),
                  child: Text(
                    AppLocalizations.of(context)!.sura_name,
                    style: Theme.of(context).textTheme.headline4,
                    textAlign: TextAlign.center,
                  ),
                ),
              ],
            ),
          ],
        ),
        // Divider(
        //   color:Theme.of(context).accentColor,
        //   thickness: 3,
        //   height:1.5,
        // ),
        // Row(
        //   mainAxisAlignment:MainAxisAlignment.spaceAround,
        //   children:[
        //     Text('Verses Number',
        //       style:Theme.of(context).textTheme.headline6,
        //     ),
        //     Container(
        //       width:3,
        //       height:45,
        //       color:Theme.of(context).accentColor,
        //     ),
        //     Text(
        //       AppLocalizations.of(context)!.sura_name,
        //       style:Theme.of(context).textTheme.headline6,
        //     ),
        //   ],
        // ),
        // // Divider(
        // //   color: Theme.of(context).accentColor,
        // //   thickness: 3,
        // //   height:1.5,
        // // ),
        Expanded(
          child: ListView.separated(
            itemBuilder: (context, index) => Table(
              border: TableBorder(
                verticalInside:
                    BorderSide(width: 3, color: Theme.of(context).accentColor),
              ),
              children: [
                TableRow(
                  children: [
                    Padding(
                      padding: const EdgeInsets.all(10.0),
                      child: Text(
                        textAlign: TextAlign.center,
                        numOfAyah[index],
                        style: Theme.of(context).textTheme.headline4,
                      ),
                    ),
                    SuraTitleWidget(title: names[index], index: index),
                  ],
                ),
              ],
            ),

            //     Row(
            //   mainAxisAlignment:MainAxisAlignment.spaceAround,
            //   children:[
            //     Text(
            //       numOfAyah[index],
            //       style:Theme.of(context).textTheme.headline4,
            //     ),
            //     SuraTitleWidget(title: names[index], index: index),
            //   ],
            // ),

            itemCount: names.length,
            separatorBuilder: (context, index) => Container(
              margin: EdgeInsets.symmetric(horizontal: 40),
              width: double.infinity,
              height: 0,
              color: Theme.of(context).accentColor,
            ),
          ),
        ),
      ],
    );
  }
}
